configMapData:
  SERVERS: '[{ "url": "http://a46b3f6038f8646f08793f724206d017-1372074634.us-east-1.elb.amazonaws.com", "description": "AWS EKS Cluster"}]'
  PORT_SERVER: "8080"

image:
  repository: "301067586589.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-lanchonete/api-docs"
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

replicaCount: 1
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"
