services:
  lanchonete-swagger:
    build:
      context: .
    container_name: lanchonete-swagger
    environment:
      PORT_SERVER: ${PORT_SERVER}
      SERVERS: '[{ "url": "http://localhost:${CONTAINER_PORT_SERVER}", "description": "Local Development"}]'
    ports:
      - "${HOST_PORT_SERVER}:${CONTAINER_PORT_SERVER}"
    restart: always
    networks:
      - fiap
    expose:
      - ${CONTAINER_PORT_SERVER}

networks:
  fiap:
    driver: bridge
