paths:
  /orders:
    get:
      summary: Lista de pedidos priorizados por status e data de criação
      tags:
        - Pedidos
      responses:
        "200":
          description: Lista dos pedidos priorizados por status 'Pronto', 'Em preparação' e 'Recebido', ordenados por data de criação
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "500":
          description: Erro interno do servidor
    post:
      summary: Cria um novo pedido
      tags:
        - Pedidos
      requestBody:
        description: Payload para criação de pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: integer
                  nullable: true
                  description: ID do cliente ou 'null' para clientes não identificados
              required:
                - customerId
      responses:
        "201":
          description: Pedido criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Payload inválido
        "500":
          description: Erro interno do servidor
  /orders/all:
    get:
      summary: Lista todos os pedidos
      tags:
        - Pedidos
      responses:
        "200":
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "500":
          description: Erro interno do servidor
  /orders/{orderId}:
    get:
      summary: Exibe um pedido pelo ID
      parameters:
        - in: path
          name: orderId
          required: true
          description: ID do pedido
          schema:
            type: integer
      tags:
        - Pedidos
      responses:
        "200":
          description: Pedido com ID informado foi encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "500":
          description: Erro interno do servidor
  /orders/{orderId}/checkout:
    post:
      summary: Finaliza um pedido
      parameters:
        - in: path
          name: orderId
          required: true
          description: ID do pedido
          schema:
            type: integer
      tags:
        - Pedidos
      responses:
        "200":
          description: Pedido finalizado
        "400":
          description: Não foi possivel finalizar o pedido pois está vazio.
        "404":
          description: Pedido não encontrado
        "500":
          description: Erro interno do servidor
  /orders/{orderId}/status:
    post:
      summary: Permite a atualização do status do pedido
      parameters:
        - in: path
          name: orderId
          required: true
          description: ID do pedido
          schema:
            type: integer
      tags:
        - Pedidos
      requestBody:
        description: Payload para atualização do status do pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  description: Novo status do pedido
                  $ref: "#/components/schemas/OrderStatus"
                  example: RECEIVED | PREPARING | DONE | FINISHED
              required:
                - status
      responses:
        "200":
          description: Pedido atualizado
        "400":
          description: Não foi possivel atualizar o pedido pois está vazio ou o status informado é inválido.
        "404":
          description: Pedido não encontrado
        "500":
          description: Erro interno do servidor
  /orders/{orderId}/payment_status:
    get:
      summary: Retorna o status do pagamento do pedido
      parameters:
        - in: path
          name: orderId
          required: true
          description: ID do pedido
          schema:
            type: integer
      tags:
        - Pedidos
      responses:
        "200":
          description: Status de pagamento do pedido
          content:
            application/json:
              schema:
                type: string
                $ref: "#/components/schemas/OrderPaymentsStatus"
        "404":
          description: Pedido não encontrado
        "500":
          description: Erro interno do servidor
  /orders/{orderId}/items:
    post:
      summary: Cria um novo item no pedido
      tags:
        - Pedidos
      parameters:
        - in: path
          name: orderId
          required: true
          description: ID do pedido
          schema:
            type: integer
      requestBody:
        description: Payload para criar um item no pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                  description: ID do Produto
                  example: 1
                quantity:
                  type: integer
                  minimum: 1
                  description: Quantidade do Produto
                  example: 2
              required:
                - productId
                - quantity
      responses:
        "201":
          description: Exibe o pedido com o item criado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Não foi possivel adicionar item pois o pedido já foi fechado ou o produto não existe.
        "404":
          description: Pedido não encontrado
        "500":
          description: Erro interno do servidor
  /orders/{orderId}/items/{itemId}:
    put:
      summary: Atualiza um item existente do pedido
      tags:
        - Pedidos
      parameters:
        - in: path
          name: orderId
          required: true
          description: ID do pedido
          schema:
            type: integer
        - in: path
          name: itemId
          required: true
          description: ID do item do pedido
          schema:
            type: integer
      requestBody:
        description: Payload para atualizar um item no pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  minimum: 1
                  description: Quantidade do item no pedido
                  example: 2
              required:
                - quantity
      responses:
        "200":
          description: Exibe o pedido com o item atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Não foi possivel atualizar o item pois o pedido já foi fechado
        "404":
          description: Item não encontrado
        "500":
          description: Erro interno do servidor
    delete:
      summary: Remove um item existente do pedido
      tags:
        - Pedidos
      parameters:
        - in: path
          name: orderId
          required: true
          description: ID do pedido
          schema:
            type: integer
        - in: path
          name: itemId
          required: true
          description: ID do item no pedido
          schema:
            type: integer
      responses:
        "204":
          description: Item removido com sucesso
          content:
            application/json: {}
        "400":
          description: Não foi possivel atualizar o item pois o pedido já foi fechado
        "404":
          description: Item não encontrado
        "500":
          description: Erro interno do servidor
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: ID do Pedido
          example: 1
        elapsedTime:
          type: integer
          description: Tempo desde a criação do pedido em milisegundos
          example: 1501767
        customerId:
          type: integer
          nullable: true
          description: ID do Cliente ou null para clientes não identificados
          example: 1
        code:
          type: string
          description: Código do Pedido
          example: 9999
        status:
          $ref: "#/components/schemas/OrderStatus"
          example: CREATED
        items:
          type: array
          description: Itens do Pedido
          items:
            $ref: "#/components/schemas/Item"

    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: ID do Item
        orderId:
          type: integer
          example: 1
          description: ID do Pedido
        productId:
          type: integer
          example: 1
          description: ID do Produto
        productName:
          type: string
          example: Hamburguer
          description: Nome do Produto
        productDescription:
          type: string
          example: Hamburguer Classico
          description: Descrição do Produto
        unitPrice:
          type: number
          format: float
          example: 12.99
          description: Preço Unitário
        quantity:
          type: integer
          example: 2
          description: Quantidade do Item
        totalPrice:
          type: number
          format: float
          example: 24.98
          description: Preço Total do Item

    OrderStatus:
      type: string
      description: Status do Pedido
      enum:
        - CREATED
        - PENDING_PAYMENT
        - PAYED
        - RECEIVED
        - PREPARING
        - DONE
        - FINISHED

    OrderPaymentsStatus:
      type: string
      description: Status do Pagamento do Pedido
      enum:
        - PENDING
        - DENIED
        - APPROVED
